name: Parliament Bill Pipeline

on:
  push:
    paths:
      - 'pbills/*.py'
      - 'sbills/*.py'
      - 'requirements.txt'
  
  schedule:
    - cron: '0 18 * * 1-5'  # Runs every weekday at 6 PM
  workflow_dispatch:

jobs:

  scrape_and_save_pbills:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        
    
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install Poppler and Tesseract
      run: sudo apt-get update && sudo apt-get install -y poppler-utils 
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scrape (pbills)
      run: python pbills/scrape.py
        
    - name: Run Extraction (pbills) 
      run: python pbills/extraction.py
        
    - name: Run Save to Firestore (pbills)
      env:
       FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
       FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      run: python pbills/save_to_firestore_add_pdf.py
        
    - name: Run Save to Firestore Fields (pbills)
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        OPENAIKEY: ${{ secrets.OPENAIKEY }}
      run: python pbills/save_to_firestore_fields.py

    - name: Check for changes (pbills)
      id: git-check
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV
        
    - name: Commit changes (pbills) and push if changes
      if: env.changes == 'true'
      run: |
        git commit -m "Updated Parliament Bill Pipeline"
        git push

  scrape_and_save_sbills:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scrape (sbills)
      run: python sbills/scrape.py
        
    - name: Run Extraction (sbills)
      run: python sbills/extraction.py
        
    - name: Run Save to Firestore (sbills)
      env:
       FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
       FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      run: python sbills/save_to_firestore_add_pdf.py
        
    - name: Run Save to Firestore Fields (sbills)
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        OPENAIKEY: ${{ secrets.OPENAIKEY }}   
      run: python sbills/save_to_firestore_fields.py
        
    - name: Check for changes (sbills)
      id: git-check
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV
        
    - name: Commit changes (sbills) and push if changes
      if: env.changes == 'true'
      run: |
        git commit -m "Updated Senate Bill Pipeline"
        git push
